--- # represents yml file
name: Checks

on: [push] #trigger

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-22.04 # runner - not running on 20.04 so updated
    steps: # steps are different things that run for jobs
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test" # runs unit test on projects
      - name: Lint
        run: docker-compose run --rm sh -c "flake8"

